//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTV_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDTV_Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;d p=&quot;&lt;-p-&gt;&quot; user=&quot;&lt;-user-&gt;&quot;&gt;&lt;-text-&gt;&lt;/d&gt; 的本地化字符串。
        /// </summary>
        internal static string LiveChat_d {
            get {
                return ResourceManager.GetString("LiveChat_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;gift ts=&quot;&lt;-ts-&gt;&quot; user=&quot;&lt;-user-&gt;&quot; uid=&quot;&lt;-uid-&gt;&quot; giftname=&quot;&lt;-giftname-&gt;&quot; giftcount=&quot;&lt;-giftcount-&gt;&quot;/&gt; 的本地化字符串。
        /// </summary>
        internal static string LiveChat_gift {
            get {
                return ResourceManager.GetString("LiveChat_gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;guard ts=&quot;&lt;-ts-&gt;&quot; user=&quot;&lt;-user-&gt;&quot; uid=&quot;&lt;-uid-&gt;&quot; level=&quot;&lt;-level-&gt;&quot; count=&quot;&lt;-count-&gt;&quot;/&gt; 的本地化字符串。
        /// </summary>
        internal static string LiveChat_guard {
            get {
                return ResourceManager.GetString("LiveChat_guard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;sc ts=&quot;&lt;-ts-&gt;&quot; user=&quot;&lt;-user-&gt;&quot; uid=&quot;&lt;-uid-&gt;&quot; price=&quot;&lt;-price-&gt;&quot; time=&quot;&lt;-time-&gt;&quot;&gt;&lt;-text-&gt;&lt;/sc&gt; 的本地化字符串。
        /// </summary>
        internal static string LiveChat_sc {
            get {
                return ResourceManager.GetString("LiveChat_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;#s&quot;?&gt;
        ///&lt;i&gt;
        ///&lt;chatserver&gt;chat.bilibili.com&lt;/chatserver&gt;
        ///&lt;chatid&gt;0&lt;/chatid&gt;
        ///&lt;mission&gt;0&lt;/mission&gt;
        ///&lt;maxlimit&gt;2147483647&lt;/maxlimit&gt;
        ///&lt;state&gt;0&lt;/state&gt;
        ///&lt;app&gt;&lt;-app-&gt;&lt;/app&gt;
        ///&lt;real_name&gt;&lt;-name-&gt;&lt;/real_name&gt;
        ///&lt;time&gt;&lt;-time-&gt;&lt;/time&gt;
        ///&lt;roomid&gt;&lt;-roomid-&gt;&lt;/roomid&gt;
        ///&lt;source&gt;k-v&lt;/source&gt;
        ///&lt;LiveChatRecordInfo roomid=&quot;&lt;-roomid-&gt;&quot; shortid=&quot;0&quot; name=&quot;&lt;-name-&gt;&quot; title=&quot;&lt;-title-&gt;&quot;/&gt;
        ///&lt;XmlStyle&gt;&lt;z:stylesheet version=&quot;1.0&quot; id=&quot;s&quot; xml:id=&quot;s&quot; xmlns:z=&quot;htt [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string LiveChatRecordInfo {
            get {
                return ResourceManager.GetString("LiveChatRecordInfo", resourceCulture);
            }
        }
    }
}
