name: DDTV_GUI

on:
  push:
    branches: [ master ]
    paths:
      - 'DDTV_GUI/**'
      - '.github/workflows/DDTV_GUI.yml'
      - '!**/README.md'
  pull_request:
    branches: [ master ]
    paths:
      - 'DDTV_GUI/**'
      - '.github/workflows/DDTV_GUI.yml'
      - '!**/README.md'

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: DDTV.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore $env:Solution_Name

    - name: Build App
      run: cd DDTV_GUI && msbuild /property:Configuration=$env:Configuration /p:DebugType=None
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload debug release
      uses: actions/upload-artifact@main
      with:
        name: DDTV_GUI_debug
        path: D:\a\DDTV\DDTV\DDTV_GUI\bin\Release\net6.0-windows
